config/routes.rb
Travel::Application.routes.draw do
  get "planner/index"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to:'static_pages#home'

  match '/refresh', to: 'planner#refresh'
  match '/test', to:'planner#update'
  match '/about', to:'static_pages#about'
  match '/home', to:'static_pages#home'
  match '/planner', to:'planner#index'
 
  resources :sessions, only: [:new, :create, :destroy]
 
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 
  match '/signup', to:'users#new'

  resources :activities

  resources :restaurants

 

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
  attr_accessible :activity, :category, :age, :budget, 
    :description, :info_url, :name, :rating, 
    :size, :tag, :time, :tourist, :location

  scope :lunch, where("category = 'l'")
  scope :dinner, where("category = 'd'")

  scope :boston, where("location = 'b'")
  scope :newyork, where("location = 'nyc'")
  scope :sanfran, where("location = 'sf'")

  scope :b1, order("budget asc")
  scope :b2, where("budget <=2").order("budget desc")
  scope :b3, order("budget desc")

  scope :g1, order("size asc")
  scope :g2, where("size <=2").order("size desc")
  scope :g3, order("size desc")

  scope :a1, order("age asc")
  scope :a2, where("age <=2").order("age desc")
  scope :a3, order("age desc")

  scope :l1, order("activity asc")
  scope :l2, where("activity <=2").order("activity desc")
  scope :l3, order("activity desc")

  scope :t1, order("tourist asc")
  scope :t2, where("tourist <=2").order("tourist desc")
  scope :t3, order("tourist desc")

  scope :rate, order("rating desc")

  def self.lsearching(b,g,a,l,t,loc)
    @lrestaurants = eval ("Restaurant." + "lunch." + b + "." + g + "." + a + "." + l + "." + t + "." + loc)
  #@restaurants = Restaurant.rate
  end
  def self.dsearching(b,g,a,l,t,loc)
    @drestaurants = eval ("Restaurant." + "dinner." + b + "." + g + "." + a + "." + l + "." + t + "." + loc)
  #@restaurants = Restaurant.rate
  end

end

require 'csv'
    CSV.foreach('app/assets/sforest.csv',  "r:ISO-8859-1") do |row|
        record = Restaurant.new(
            :name   => row[0], 
            :category => row[1],
            :description => row[11],
            :info_url => row[3],
            :time => row[4],
            :size => row[5],
            :activity => row[6],
            :budget => row[7],
            :age => row[8],
            :tourist => row[9],
            :rating => row[10],
            :tag => row[11],
            :location => row[12]
        )
        record.save!
    end

    CSV.foreach('app/assets/nycrestaurant.csv',  "r:ISO-8859-1") do |row|
        record = Restaurant.new(
            :name   => row[0], 
            :category => row[1],
            :description => row[11],
            :info_url => row[3],
            :time => row[4],
            :size => row[5],
            :activity => row[6],
            :budget => row[7],
            :age => row[8],
            :tourist => row[9],
            :rating => row[10],
            :tag => row[11],
            :location => row[12]
        )
        record.save!
    end

    CSV.foreach('app/assets/bostonrest.csv',  "r:ISO-8859-1") do |row|
        record = Restaurant.new(
            :name   => row[0], 
            :category => row[11],
            :description => row[1],
            :info_url => row[3],
            :time => row[4],
            :size => row[5],
            :activity => row[6],
            :budget => row[7],
            :age => row[8],
            :tourist => row[9],
            :rating => row[10],
            :tag => row[2],
            :location => row[12]
        )
        record.save!
    end


# require 'csv-mapper'

# include CsvMapper

# results = import('../assets/nycrest.csv') do
#   map_to Restaurant # Map to the Person ActiveRecord class (defined above) instead of the default OpenStruct.
#   after_row lambda{|row, restaurant| restaurant.save }  # Call this lambda and save each record after it's parsed.

#   start_at_row 2
#   [name, category, description, info_url, time, size, activity, budget, age, tourist, rating, tag, location]
# end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def filter (budget)
    @restaurant = Restaurant.scoped
    @restaurant = @restaurant.budget(params[:budget])
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :info_url %><br />
    <%= f.text_field :info_url %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :activity %><br />
    <%= f.text_field :activity %>
  </div>
  <div class="field">
    <%= f.label :budget %><br />
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :tourist %><br />
    <%= f.text_field :tourist %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_area :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Boston restaurants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
<!--    <th>Info url</th>
    <th>Time</th>
    <th>Size</th>
    <th>Activity</th>
    <th>Budget</th>
    <th>Age</th>
    <th>Tourist</th>-->
    <th>Rating</th>
    <th>Tag</th>
    <th>Location</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @restaurants.each do |restaurant| %>
  <tr>
    <td><%= restaurant.name %></td>
    <td><%= restaurant.description %></td>
    <td><%= restaurant.info_url %></td>
    <td><%= restaurant.time %></td>
    <td><%= restaurant.size %></td>
    <td><%= restaurant.activity %></td>
    <td><%= restaurant.budget %></td>
    <td><%= restaurant.age %></td>
    <td><%= restaurant.tourist %></td>
    <td><%= restaurant.rating %></td>
    <td><%= restaurant.tag %></td>
    <td><%= restaurant.location %></td>
    <!--
    <td><%= link_to 'Show', restaurant %></td>
    <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
    <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  </tr>
<% end %>
</table>

<br />

<!--<%= link_to 'New Restaurant', new_restaurant_path %>-->

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @restaurant.name %>
</p>

<p>
  <b>Description:</b>
  <%= @restaurant.description %>
</p>

<p>
  <b>Info url:</b>
  <%= @restaurant.info_url %>
</p>

<p>
  <b>Time:</b>
  <%= @restaurant.time %>
</p>

<p>
  <b>Size:</b>
  <%= @restaurant.size %>
</p>

<p>
  <b>Activity:</b>
  <%= @restaurant.activity %>
</p>

<p>
  <b>Budget:</b>
  <%= @restaurant.budget %>
</p>

<p>
  <b>Age:</b>
  <%= @restaurant.age %>
</p>

<p>
  <b>Tourist:</b>
  <%= @restaurant.tourist %>
</p>

<p>
  <b>Rating:</b>
  <%= @restaurant.rating %>
</p>

<p>
  <b>Tag:</b>
  <%= @restaurant.tag %>
</p>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>