config/routes.rb
Travel::Application.routes.draw do
  get "planner/index"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to:'static_pages#home'

  match '/refresh', to: 'planner#refresh'
  match '/test', to:'planner#update'
  match '/about', to:'static_pages#about'
  match '/home', to:'static_pages#home'
  match '/planner', to:'planner#index'
 
  resources :sessions, only: [:new, :create, :destroy]
 
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 
  match '/signup', to:'users#new'

  resources :activities

  resources :restaurants

 

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :activity, :age, :budget, :category, :description, 
  :info_url, :name, :rating, :size, :tag, :time, :tourist, :location

  scope :boston, where("location = 'b'")
  scope :newyork, where("location = 'nyc'")
  scope :sanfran, where("location = 'sf'")

  scope :b1, order("budget asc")
  scope :b2, where("budget <=2").order("budget desc")
  scope :b3, order("budget desc")

  scope :g1, order("size asc")
  scope :g2, where("size <=2").order("size desc")
  scope :g3, order("size desc")

  scope :a1, order("age asc")
  scope :a2, where("age <=2").order("age desc")
  scope :a3, order("age desc")

  scope :l1, order("activity asc")
  scope :l2, where("activity <=2").order("activity desc")
  scope :l3, order("activity desc")

  scope :t1, order("tourist asc")
  scope :t2, where("tourist <=2").order("tourist desc")
  scope :t3, order("tourist desc")

  scope :rate, order("rating desc")

  def self.searching(b,g,a,l,t,loc)
 	@activities = eval ("Activity." + b + "." + g + "." + a + "." + l + "." + t + "." + loc)
 	#@restaurants = Restaurant.rate
  end

end

require 'csv'
    CSV.foreach('app/assets/nycact.csv',  "r:ISO-8859-1") do |row|
        record = Activity.new(
            :name   => row[0], 
            :category => row[1],
            :description => row[2],
            :info_url => row[3],
            :time => row[4],
            :size => row[5],
            :activity => row[6],
            :budget => row[7],
            :age => row[8],
            :tourist => row[9],
            :rating => row[10],
            :location => row[11]
        )
        record.save!
    end
    CSV.foreach('app/assets/sfoact.csv',  "r:ISO-8859-1") do |row|
        record = Activity.new(
            :name   => row[0], 
            :category => row[1],
            :description => row[2],
            :info_url => row[3],
            :time => row[4],
            :size => row[5],
            :activity => row[6],
            :budget => row[7],
            :age => row[8],
            :tourist => row[9],
            :rating => row[10],
            :location => row[11]
        )
        record.save!
    end
    CSV.foreach('app/assets/bact.csv',  "r:ISO-8859-1") do |row|
        record = Activity.new(
            :name   => row[0], 
            :category => row[1],
            :description => row[2],
            :info_url => row[3],
            :time => row[4],
            :size => row[5],
            :activity => row[6],
            :budget => row[7],
            :age => row[8],
            :tourist => row[9],
            :rating => row[10],
            :location => row[12]
        )
        record.save!
      end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :info_url %><br />
    <%= f.text_field :info_url %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :activity %><br />
    <%= f.text_field :activity %>
  </div>
  <div class="field">
    <%= f.label :budget %><br />
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :tourist %><br />
    <%= f.text_field :tourist %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_area :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Description</th>
    <th>Info url</th>
    <th>Time</th>
    <th>Size</th>
    <th>Activity</th>
    <th>Budget</th>
    <th>Age</th>
    <th>Tourist</th>
    <th>Rating</th>
    <th>Tag</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.name %></td>
    <td><%= activity.category %></td>
    <td><%= activity.description %></td>
    <td><%= activity.info_url %></td>
    <td><%= activity.time %></td>
    <td><%= activity.size %></td>
    <td><%= activity.activity %></td>
    <td><%= activity.budget %></td>
    <td><%= activity.age %></td>
    <td><%= activity.tourist %></td>
    <td><%= activity.rating %></td>
    <td><%= activity.tag %></td>
    <td><%= activity.location %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @activity.name %>
</p>

<p>
  <b>Category:</b>
  <%= @activity.category %>
</p>

<p>
  <b>Description:</b>
  <%= @activity.description %>
</p>

<p>
  <b>Info url:</b>
  <%= @activity.info_url %>
</p>

<p>
  <b>Time:</b>
  <%= @activity.time %>
</p>

<p>
  <b>Size:</b>
  <%= @activity.size %>
</p>

<p>
  <b>Activity:</b>
  <%= @activity.activity %>
</p>

<p>
  <b>Budget:</b>
  <%= @activity.budget %>
</p>

<p>
  <b>Age:</b>
  <%= @activity.age %>
</p>

<p>
  <b>Tourist:</b>
  <%= @activity.tourist %>
</p>

<p>
  <b>Rating:</b>
  <%= @activity.rating %>
</p>

<p>
  <b>Tag:</b>
  <%= @activity.tag %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>