config/routes.rb
Travel::Application.routes.draw do
  get "planner/index"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to:'static_pages#home'

  match '/refresh', to: 'planner#refresh'
  match '/test', to:'planner#update'
  match '/about', to:'static_pages#about'
  match '/home', to:'static_pages#home'
  match '/planner', to:'planner#index'
 
  resources :sessions, only: [:new, :create, :destroy]
 
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 
  match '/signup', to:'users#new'

  resources :activities

  resources :restaurants

 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Site made for 6.470 competition at MIT by Victoria Li, Nitya Subramanian, Anubhav Jain.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <link rel = "shortcut icon" herf="images/icon.png"/>
  <div class="navbar-inner">
    <div class="container">      
      <nav>
        <ul class="nav pull-right">

          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "About",    about_path %></li>
          <% if signed_in? %>
            <li><%= link_to current_user.name, current_user%></li>
              <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
            
            <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <% end %>


        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link type="text/css" rel="stylesheet" href="jquery.dropdown.css" />
<script type="text/javascript" src="jquery.dropdown.js"></script>
<script type="text/javascript" src="jQuerylink" ></script>
<script src="jqui.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>


<script src="js/jquery-1.8.0.js"></script>
<link rel="stylesheet" src="jqui.css" />
<html>
<head>
	<meta charset='utf-8' />
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media =>"all" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key,value| %>
		<div class="alert aler - <%= key%>"> <%= value %></div>
		<% end %>
<%= yield %>

</div>
</head>

<body>
	<br/>
	<br/>
	<br/>
	<br/>
<div id="footer">
	Created by Victoria Li, Nitya Subramanian, Anubhav Jain
</div>
</body>
</html>